In [1]:
import pandas as pd

incidents = pd.read_csv('California_Fire_Incidents.csv')
incidents

AcresBurned  Active                                          AdminUnit  \
0        257314.0   False  Stanislaus National Forest/Yosemite National Park   
1         30274.0   False  USFS Angeles National Forest/Los Angeles Count...   
2         27531.0   False  CAL FIRE Riverside Unit / San Bernardino Natio...   
3         27440.0   False                              Tahoe National Forest   
4         24251.0   False                       Ventura County Fire/CAL FIRE   
...           ...     ...                                                ...   
1631          9.0   False                   CAL FIRE / Riverside County Fire   
1632          2.0   False                  CAL FIRE Nevada-Yuba-Placer Unit    
1633          NaN   False               Yolo County Fire Protection District   
1634          NaN   False                   Camp Pendleton Marine Corps Base   
1635          NaN   False                           Bureau of Indian Affairs   

      AirTankers  ArchiveYear  CalFireIncident  \
0            NaN         2013             True   
1            NaN         2013             True   
2            NaN         2013             True   
3            NaN         2013            False   
4            NaN         2013             True   
...          ...          ...              ...   
1631         NaN         2019             True   
1632         NaN         2019             True   
1633         NaN         2019            False   
1634         NaN         2019            False   
1635         NaN         2019            False   

                               CanonicalUrl  \
0            /incidents/2013/8/17/rim-fire/   
1     /incidents/2013/5/30/powerhouse-fire/   
2       /incidents/2013/7/15/mountain-fire/   
3       /incidents/2013/8/10/american-fire/   
4         /incidents/2013/5/2/springs-fire/   
...                                     ...   
1631      /incidents/2019/10/10/eagle-fire/   
1632        /incidents/2019/6/28/long-fire/   
1633      /incidents/2019/11/25/cashe-fire/   
1634        /incidents/2019/10/22/oak-fire/   
1635    /incidents/2019/10/14/johnson-fire/   

                                     ConditionStatement ControlStatement  \
0                                                   NaN              NaN   
1                                                   NaN              NaN   
2                                                   NaN              NaN   
3                                                   NaN              NaN   
4     Acreage has been reduced based upon more accur...              NaN   
...                                                 ...              ...   
1631                                                NaN              NaN   
1632                                                NaN              NaN   
1633                                                NaN              NaN   
1634                                                NaN              NaN   
1635  As of 10:00 p.m. on 10/16, the fire is 90% con...              NaN   

         Counties  ...                                     SearchKeywords  \
0        Tuolumne  ...  Rim Fire, Stanislaus National Forest, Yosemite...   
1     Los Angeles  ...  Powerhouse Fire, May 2013, June 2013, Angeles ...   
2       Riverside  ...  Mountain Fire, July 2013, Highway 243, Highway...   
3          Placer  ...  American Fire, August 2013, Deadwood Ridge, Fo...   
4         Ventura  ...  Springs Fire, May 2013, Highway 101, Camarillo...   
...           ...  ...                                                ...   
1631    Riverside  ...                                                NaN   
1632       Nevada  ...                                                NaN   
1633         Yolo  ...                                                NaN   
1634    San Diego  ...                                                NaN   
1635    Riverside  ...                                                NaN   

                   Started     Status  St

In [4]:
rows=incidents.shape[0]
columns=incidents.shape[1]

In [5]:
rows

1636

In [6]:
columns

40

In [7]:
incidents.columns

Index(['AcresBurned', 'Active', 'AdminUnit', 'AirTankers', 'ArchiveYear',
       'CalFireIncident', 'CanonicalUrl', 'ConditionStatement',
       'ControlStatement', 'Counties', 'CountyIds', 'CrewsInvolved', 'Dozers',
       'Engines', 'Extinguished', 'Fatalities', 'Featured', 'Final',
       'FuelType', 'Helicopters', 'Injuries', 'Latitude', 'Location',
       'Longitude', 'MajorIncident', 'Name', 'PercentContained',
       'PersonnelInvolved', 'Public', 'SearchDescription', 'SearchKeywords',
       'Started', 'Status', 'StructuresDamaged', 'StructuresDestroyed',
       'StructuresEvacuated', 'StructuresThreatened', 'UniqueId', 'Updated',
       'WaterTenders'],
      dtype='object')

In [8]:
incidents.dtypes

AcresBurned             float64
Active                     bool
AdminUnit                object
AirTankers              float64
ArchiveYear               int64
CalFireIncident            bool
CanonicalUrl             object
ConditionStatement       object
ControlStatement         object
Counties                 object
CountyIds                object
CrewsInvolved           float64
Dozers                  float64
Engines                 float64
Extinguished             object
Fatalities              float64
Featured                   bool
Final                      bool
FuelType                 object
Helicopters             float64
Injuries                float64
Latitude                float64
Location                 object
Longitude               float64
MajorIncident              bool
Name                     object
PercentContained        float64
PersonnelInvolved       float64
Public                     bool
SearchDescription        object
SearchKeywords           object
Started 

In [10]:
incidents.tail(5)

AcresBurned  Active                             AdminUnit  AirTankers  \
1631          9.0   False      CAL FIRE / Riverside County Fire         NaN   
1632          2.0   False     CAL FIRE Nevada-Yuba-Placer Unit          NaN   
1633          NaN   False  Yolo County Fire Protection District         NaN   
1634          NaN   False      Camp Pendleton Marine Corps Base         NaN   
1635          NaN   False              Bureau of Indian Affairs         NaN   

      ArchiveYear  CalFireIncident                         CanonicalUrl  \
1631         2019             True    /incidents/2019/10/10/eagle-fire/   
1632         2019             True      /incidents/2019/6/28/long-fire/   
1633         2019            False    /incidents/2019/11/25/cashe-fire/   
1634         2019            False      /incidents/2019/10/22/oak-fire/   
1635         2019            False  /incidents/2019/10/14/johnson-fire/   

                                     ConditionStatement ControlStatement  \
1631                                                NaN              NaN   
1632                                                NaN              NaN   
1633                                                NaN              NaN   
1634                                                NaN              NaN   
1635  As of 10:00 p.m. on 10/16, the fire is 90% con...              NaN   

       Counties  ... SearchKeywords               Started     Status  \
1631  Riverside  ...            NaN  2019-10-10T12:08:00Z  Finalized   
1632     Nevada  ...            NaN  2019-06-28T15:03:04Z  Finalized   
1633       Yolo  ...            NaN  2019-11-25T12:02:02Z  Finalized   
1634  San Diego  ...            NaN  2019-10-22T19:20:44Z  Finalized   
1635  Riverside  ...            NaN  2019-10-14T15:32:20Z   Inactive   

      StructuresDamaged StructuresDestroyed  StructuresEvacuated  \
1631                NaN                 NaN                  NaN   
1632                NaN                 NaN                  NaN   
1633                NaN                 NaN                  NaN   
1634                NaN                 NaN                  NaN   
1635                NaN                 NaN                  NaN   

      StructuresThreatened                              UniqueId  \
1631                   NaN  6e93b252-99a3-4214-9921-238373b17535   
1632                   NaN  b38c0563-b321-431b-9174-6336c5a0d449   
1633                   NaN  9c26f915-1b33-422d-b30a-9eb4da6fd729   
1634                   NaN  7264a106-e0f4-41de-8fd0-3f9110431e28   
1635                   NaN  8bf75401-999f-42bd-8c0a-8db508591545   

                       Updated  WaterTenders  
1631  2019-10-10T18:11:59.733Z           NaN  
1632  2019-06-30T15:52:01.023Z           NaN  
1633   2019-12-03T16:35:20.93Z           NaN  
1634   2019-11-21T12:21:28.58Z           NaN  
1635   2019-10-30T10:14:19.58Z           NaN  

[5 rows x 40 columns]

In [11]:
incidents.describe()

AcresBurned  AirTankers  ArchiveYear  CrewsInvolved      Dozers  \
count    1633.000000   28.000000  1636.000000     171.000000  123.000000   
mean     4589.443968    4.071429  2016.608802      11.561404    7.585366   
std     27266.337722    6.399818     1.845340      14.455633   14.028616   
min         0.000000    0.000000  2013.000000       0.000000    0.000000   
25%        35.000000    2.000000  2015.000000       2.500000    1.000000   
50%       100.000000    2.000000  2017.000000       6.000000    2.000000   
75%       422.000000    4.000000  2018.000000      13.500000    5.000000   
max    410203.000000   27.000000  2019.000000      82.000000   76.000000   

          Engines  Fatalities  Helicopters    Injuries     Latitude  \
count  191.000000   21.000000    84.000000  120.000000  1636.000000   
mean    23.565445    8.619048     5.357143    3.500000    37.203975   
std     41.004424   18.529642     7.265437    3.806231   135.401380   
min      0.000000    1.000000     0.000000    0.000000  -120.258000   
25%      5.000000    1.000000     1.000000    1.000000    34.165891   
50%     11.000000    3.000000     2.000000    3.000000    37.104065   
75%     24.000000    6.000000     5.000000    4.000000    39.086808   
max    256.000000   85.000000    29.000000   26.000000  5487.000000   

         Longitude  PercentContained  PersonnelInvolved  StructuresDamaged  \
count  1636.000000            1633.0         204.000000          67.000000   
mean   -108.082642             100.0         328.553922          67.970149   
std      37.006927               0.0         521.138789         155.771975   
min    -124.196290             100.0           0.000000           0.000000   
25%    -121.768358             100.0          55.000000           1.000000   
50%    -120.461560             100.0         151.500000           6.000000   
75%    -117.474073             100.0         350.000000          49.500000   
max     118.908200             100.0        3100.000000         783.000000   

       StructuresDestroyed  StructuresEvacuated  StructuresThreatened  \
count           175.000000                  0.0             30.000000   
mean            271.788571                  NaN            522.800000   
std            1557.255963                  NaN            739.586856   
min               0.000000                  NaN              0.000000   
25%               1.000000                  NaN              0.000000   
50%               7.000000                  NaN             45.000000   
75%              41.500000                  NaN           1043.750000   
max           18804.000000                  NaN           2600.000000   

       WaterTenders  
count    146.000000  
mean       7.815068  
std       12.719251  
min        1.000000  
25%        2.000000  
50%        4.000000  
75%        6.000000  
max       79.000000

In [13]:
# Number of missing values and non missing values (actual data) in AcresBurned
incidents[  incidents['AcresBurned'].isna()   ].shape[0]

3

In [14]:
incidents['AcresBurned'].isna()

0       False
1       False
2       False
3       False
4       False
        ...  
1631    False
1632    False
1633     True
1634     True
1635     True
Name: AcresBurned, Length: 1636, dtype: bool

In [18]:
incidents['AcresBurned'].notna().sum()

1633

In [19]:
incidents['AcresBurned'].isna().value_counts()

False    1633
True        3
Name: AcresBurned, dtype: int64

In [22]:
for each_column in incidents.columns:
    print(incidents[each_column].notna().value_counts())

True     1633
False       3
Name: AcresBurned, dtype: int64
True    1636
Name: Active, dtype: int64
True    1636
Name: AdminUnit, dtype: int64
False    1608
True       28
Name: AirTankers, dtype: int64
True    1636
Name: ArchiveYear, dtype: int64
True    1636
Name: CalFireIncident, dtype: int64
True    1636
Name: CanonicalUrl, dtype: int64
False    1352
True      284
Name: ConditionStatement, dtype: int64
False    1525
True      111
Name: ControlStatement, dtype: int64
True    1636
Name: Counties, dtype: int64
True    1636
Name: CountyIds, dtype: int64
False    1465
True      171
Name: CrewsInvolved, dtype: int64
False    1513
True      123
Name: Dozers, dtype: int64
False    1445
True      191
Name: Engines, dtype: int64
True     1577
False      59
Name: Extinguished, dtype: int64
False    1615
True       21
Name: Fatalities, dtype: int64
True    1636
Name: Featured, dtype: int64
True    1636
Name: Final, dtype: int64
False    1624
True       12
Name: FuelType, dtype: int64
False    1

In [24]:
incidents['Active'].value_counts() # Active fires

False    1636
Name: Active, dtype: int64

In [28]:
# how many fires did require the use of a helicopter?
(incidents['Helicopters'] > 0).value_counts()

False    1557
True       79
Name: Helicopters, dtype: int64

In [29]:

# how many times did a helicoper was used?
incidents['Helicopters'].sum()

450.0

In [30]:
# How many different values do we have in the StructuresDamaged column?
incidents['StructuresDamaged'].unique()

array([ nan,   6.,   8.,  10.,   9.,   1.,   7.,   2.,   5.,   4.,   3.,
        28., 280.,  21., 172., 783., 317.,  44.,  26.,  55.,  60.,  64.,
        61., 341.,  12.,  16.,  88.,  27.,   0.])

In [31]:

incidents['StructuresDestroyed'].unique()
# 3.7400e+02    = 3.74 · 10 ^ 2 = 374
# 1.8804e+04    = 18804

array([       nan, 1.0000e+01, 4.0000e+01, 2.0100e+02, 1.4900e+02,
       1.0000e+00, 7.0000e+00, 0.0000e+00, 4.0000e+00, 9.0000e+00,
       8.0000e+01, 2.1000e+01, 6.0000e+00, 2.0000e+01, 6.7000e+01,
       3.0000e+00, 4.7000e+01, 1.6500e+02, 1.1000e+01, 6.9000e+01,
       9.6000e+01, 2.7000e+01, 6.8000e+01, 2.0000e+00, 2.3000e+01,
       1.6000e+01, 5.0000e+00, 7.0000e+01, 3.2100e+02, 2.8000e+01,
       3.0000e+02, 1.0630e+03, 1.3100e+02, 1.3550e+03, 1.2000e+02,
       5.6360e+03, 5.4600e+02, 3.7000e+01, 2.6400e+02, 2.5000e+01,
       7.4000e+01, 4.1000e+01, 1.5700e+02, 5.4000e+01, 1.6200e+02,
       4.8000e+01, 1.3000e+01, 2.4600e+02, 1.6140e+03, 1.8804e+04,
       1.6430e+03, 2.9000e+01, 4.2000e+01, 3.5000e+01, 8.3000e+01,
       2.4000e+01, 2.2000e+01, 1.2000e+01, 8.0000e+00, 3.7400e+02,
       1.9000e+01, 1.4000e+01])

In [34]:
incidents['StructuresEvacuated'].unique()


array([nan])

In [35]:
incidents['StructuresThreatened'].unique()


array([  nan,    0.,  176.,   50., 1200., 1100.,   40.,   54., 2600.,
        540.,    5., 1050., 1025.,   10.,   24.])

In [50]:
#-1 means no idea of it at all
#incidents['StructuresDestroyed'].replace(np.NaN, -1)
incidents['StructuresDestroyed']=incidents['StructuresDestroyed'].fillna(-1).apply( lambda number : int(number) )
# incidents['StructuresDestroyed'].fillna(-1).astype( int )

In [51]:
incidents['StructuresDestroyed'].unique()

array([   -1,    10,    40,   201,   149,     1,     7,     0,     4,
           9,    80,    21,     6,    20,    67,     3,    47,   165,
          11,    69,    96,    27,    68,     2,    23,    16,     5,
          70,   321,    28,   300,  1063,   131,  1355,   120,  5636,
         546,    37,   264,    25,    74,    41,   157,    54,   162,
          48,    13,   246,  1614, 18804,  1643,    29,    42,    35,
          83,    24,    22,    12,     8,   374,    19,    14])

In [52]:
#Calculate the mean of this column?
#
# 10 structures were destroyed - small incidents
# 10-50 - medium incidents
# 50-500 - important incidents
# +500 - really important incidents

kind_of_fire = pd.cut( incidents['StructuresDestroyed'], (-2,-1,10, 50, 500, 999999999) , labels=['na', 'small', 'medium', 'important', 'really important'] )
kind_of_fire.value_counts()

na                  1461
small                 98
medium                38
important             27
really important      12
Name: StructuresDestroyed, dtype: int64

In [53]:
# we need to add that column to our dataframe
# groupby function 
# sum function
incidents['kind_of_fire']=kind_of_fire

In [59]:
incidents.groupby('kind_of_fire').sum()['Helicopters']
incidents.groupby('kind_of_fire')['Helicopters'].sum() # Faster

kind_of_fire
na                  217.0
small               132.0
medium               81.0
important            18.0
really important      2.0
Name: Helicopters, dtype: float64

In [81]:
#incidents['ConditionStatement'].unique()

In [78]:
import re

def cleanUp(a_text):
    PATTERN = '((<[a-zA-Z0-9 /_=:".?-]*>)|[\n\r\t ])+'
    a_clean_text=re.sub( PATTERN , " ", str(a_text))
    return a_clean_text


In [80]:
incidents['ConditionStatement'].apply( cleanUp ).unique()
incidents['ConditionStatement']=incidents['ConditionStatement'].apply( cleanUp )
incidents['ConditionStatement'].unique()

array(['nan',
       'Acreage has been reduced based upon more accurate mapping. Continue to mop up in areas very visible to public. Continue demobilization, fire damage inspections, and suppression repair. ',
       'Firefighters closed the containment lines today. Large scale demobilization of incident resources continues. Command of the incident will be turned over to Riverside County effective Tuesday August 8th. Silent Valley RV Club remains closed. For questions regarding the closure, please the Silent Valley RV Club.',
       'Fire suppression repair will continue throughout the weekend. Fireline personnel will continue mopping up the interior of the fire area until fully controlled. All hiking trails within the Ishi Wilderness are temporarily closed, but are scheduled to be reopened to the public this Saturday, August 31, 2013.',
       'California Incident Management Team 5 will transition the Clover incident back to the Shasta-Trinity Unit this afternoon. All evacuations and 

In [86]:
incidents['Started']=pd.to_datetime(incidents['Started'])

In [87]:
incidents['Updated']=pd.to_datetime(incidents['Updated'])

In [88]:
incidents['Updated']

0             2013-09-06 18:30:00+00:00
1             2013-06-08 18:30:00+00:00
2             2013-07-30 18:00:00+00:00
3             2013-08-30 08:00:00+00:00
4             2013-05-11 06:30:00+00:00
                     ...               
1631   2019-10-10 18:11:59.733000+00:00
1632   2019-06-30 15:52:01.023000+00:00
1633   2019-12-03 16:35:20.930000+00:00
1634   2019-11-21 12:21:28.580000+00:00
1635   2019-10-30 10:14:19.580000+00:00
Name: Updated, Length: 1636, dtype: datetime64[ns, UTC]

In [91]:
# Incidents from 2019-07
incidents[(incidents['Updated'] > "2019-07-02")]['Updated']


182    2019-11-12 10:27:44.360000+00:00
183    2019-11-12 10:27:44.360000+00:00
237    2019-11-12 10:25:56.523000+00:00
566    2019-07-09 14:50:56.033000+00:00
622    2019-10-25 08:54:34.150000+00:00
                     ...               
1629   2019-07-03 13:12:42.677000+00:00
1631   2019-10-10 18:11:59.733000+00:00
1633   2019-12-03 16:35:20.930000+00:00
1634   2019-11-21 12:21:28.580000+00:00
1635   2019-10-30 10:14:19.580000+00:00
Name: Updated, Length: 265, dtype: datetime64[ns, UTC]

In [93]:
pd.to_datetime("2019-07-02")

Timestamp('2019-07-02 00:00:00')

In [98]:
#incidents[(incidents['Updated'] > pd.to_datetime("2019-07-02"))]['Updated']
#incidents['Updated'].apply( lambda date: date > pd.to_datetime("2019-07-02") )

In [ ]:
# "2013-09-06T18:30:00Z" -> 
# A computer requires at least 1 byte to represent each char
# How many different things could be stored in 1 byte ?
# How many different chars humans use nowadays? 6000 

# This string requires 20 bytes 
# How many bytes are needed to store a date? 8 bytes

CPU 64bits ***
    32bits